### PR TITLE
Feature AZ filter on all addresses

### PR DESCRIPTION
**Pull request by KingGorrin**
# What?

A non-pillar user has to switch the selected address to see projects on another address. While a pillar user sees all projects for all addresses.

## Example
An user with 3 addresses
Address 1 has a pillar registration and 3 projects
Address 2 has 1 project
Address 3 has 1 project

- When address 1 is selected, the user sees all 5 projects when activating the 'My projects' filter tag.
- When address 2 or 3 is selected, the user only sees project 1 when activating the 'My projects' filter tag.

# Why?

When address 1 is selected the user is considerd a pillar user, otherwise a non-pillar user.

The 'My projects' filter tag, filters on all user addresses, but as a non-pillar owner the result set gets filtert down in the `_filterProjectsAccordingToPillarInfo` function to all active projects or projects owned by the selected address.

# How?

With the following change the situation would be equal to that of a pillar user and the user would not have to change the selected address to see all his owned projects.

This above solution brings non-pillar users in line with pillar users, but eventually one does need to switch to the owned address when creating phases. This applies to both non-pillar and pillar users. This could be a bit confusing when someone is not familiar with the concept. The "create phase" will only be visible when the address of the project owner is selected.

Pros
- Allows the user to see all projects without the need to switch.

Cons
- Confusing when creating phases

# Alternative solution

Bring pillar users in line with non-pillar users. Both user types only see "my projects" that match the current selected address.

### CODE REVIEW

**Comment by georgezgeorgez** [comment]
Personally I think showing all active projects to all users by default makes sense.
It can help users keep up with what is going on in the network and encourage them to engage with the community.

Maybe a tool tip on projects owned by the user that they need to switch to the address in order to make phases.

**Comment by KingGorrin** [comment]
I agree with that. Switching between addresses could be more intuitive and displaying tooltips can certainly guide the user in this. I consider both features a separate change to improve address switching. Should this change wait for that feature first?

**Comment by georgezgeorgez** [comment]
@KingGorrin i will approve this
this is more subjective and as mentioned maybe requires some future work
but given that this is our binary, i'm comfortable with pushing towards what we think is subjectively better

**Review by georgezgeorgez — APPROVED** [review]

**Comment by sol-znn** [comment]
I like the change, though as you stated, it can create a confusing situation for users.

I've cloned [your branch and made adjustments](https://github.com/zenon-network/syrius/compare/master...Sol-Sanctum:syrius:az-projects-filter) to use  the project owner's address when interacting with phases.

However, I've been having trouble confirming that it works correctly on my devnet. 
Some timing issues related to AZ proposal voting periods...

Feel free to consider this update or only merge your changes for now.

**Pull request merged**
